#include <stdint.h>

#define CONSTANT_2 2
#define CONSTANT_32 32
#define CONSTANT_BIG 15485863
#define INIT_LOCALS "volatile int32_t a = 10; volatile int32_t b = 13; volatile int32_t result;" 
#define DATAPOINT1 "void datapoint1(void){  result = a + CONSTANT_2;}"
#define DATAPOINT2 "void datapoint2(void){  result = b + CONSTANT_2;}"
#define DATAPOINT3 "void datapoint3(void){  result = a + CONSTANT_32;}"
#define DATAPOINT4 "void datapoint4(void){  result = b + CONSTANT_32;}"
#define DATAPOINT5 "void datapoint5(void){  result = a + CONSTANT_BIG;}"
#define DATAPOINT6 "void datapoint6(void){  result = b + CONSTANT_BIG;}"
#define DATAPOINT7 "void datapoint7(void){  result = a - CONSTANT_2;}"
#define DATAPOINT8 "void datapoint8(void){  result = b - CONSTANT_2;}"
#define DATAPOINT9 "void datapoint9(void){  result = a - CONSTANT_32;}"
#define DATAPOINT10 "void datapoint10(void){  result = b - CONSTANT_32;}"
#define DATAPOINT11 "void datapoint11(void){  result = a - CONSTANT_BIG;}"
#define DATAPOINT12 "void datapoint12(void){  result = b - CONSTANT_BIG;}"
#define DATAPOINT13 "void datapoint13(void){  result = a * CONSTANT_2;}"
#define DATAPOINT14 "void datapoint14(void){  result = b * CONSTANT_2;}"
#define DATAPOINT15 "void datapoint15(void){  result = a * CONSTANT_32;}"
#define DATAPOINT16 "void datapoint16(void){  result = b * CONSTANT_32;}"
#define DATAPOINT17 "void datapoint17(void){  result = a * CONSTANT_BIG;}"
#define DATAPOINT18 "void datapoint18(void){  result = b * CONSTANT_BIG;}"
#define DATAPOINT19 "void datapoint19(void){  result = a / CONSTANT_2;}"
#define DATAPOINT20 "void datapoint20(void){  result = b / CONSTANT_2;}"
#define DATAPOINT21 "void datapoint21(void){  result = a / CONSTANT_32;}"
#define DATAPOINT22 "void datapoint22(void){  result = b / CONSTANT_32;}"
#define DATAPOINT23 "void datapoint23(void){  result = a / CONSTANT_BIG;}"
#define DATAPOINT24 "void datapoint24(void){  result = b / CONSTANT_BIG;}"
#define DATAPOINT25 "void datapoint25(void){  result = a % CONSTANT_2;}"
#define DATAPOINT26 "void datapoint26(void){  result = b % CONSTANT_2;}"
#define DATAPOINT27 "void datapoint27(void){  result = a % CONSTANT_32;}"
#define DATAPOINT28 "void datapoint28(void){  result = b % CONSTANT_32;}"
#define DATAPOINT29 "void datapoint29(void){  result = a % CONSTANT_BIG;}"
#define DATAPOINT30 "void datapoint30(void){  result = b % CONSTANT_BIG;}"
#define DATAPOINT31 "void datapoint31(void){  result = a << CONSTANT_2;}"
#define DATAPOINT32 "void datapoint32(void){  result = b << CONSTANT_2;}"
#define DATAPOINT33 "void datapoint33(void){  result = a << CONSTANT_32;}"
#define DATAPOINT34 "void datapoint34(void){  result = b << CONSTANT_32;}"
#define DATAPOINT35 "void datapoint35(void){  result = a << CONSTANT_BIG;}"
#define DATAPOINT36 "void datapoint36(void){  result = b << CONSTANT_BIG;}"
#define DATAPOINT37 "void datapoint37(void){  result = a >> CONSTANT_2;}"
#define DATAPOINT38 "void datapoint38(void){  result = b >> CONSTANT_2;}"
#define DATAPOINT39 "void datapoint39(void){  result = a >> CONSTANT_32;}"
#define DATAPOINT40 "void datapoint40(void){  result = b >> CONSTANT_32;}"
#define DATAPOINT41 "void datapoint41(void){  result = a >> CONSTANT_BIG;}"
#define DATAPOINT42 "void datapoint42(void){  result = b >> CONSTANT_BIG;}"
